### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JMNordeste-dev**
Updating to replace team tokens with service account link

### CODE REVIEW

**Comment by jonquil2002** [comment]
@JustinN-Replicated I just saw this request and made some minor changes. Hope it looks ok to you.

**Review by jonquil2002 — COMMENTED** [review]
I made some minor changes.

**Review by JMNordeste-dev — COMMENTED** [review]
lgtm

**Comment by JMNordeste-dev** [comment]
Heads up though, I can't approve.

**Review by jonquil2002 — APPROVED** [review]

**Comment by jonquil2002** [comment]
@jordan - sorry, I didn't know I needed to approve. It's done now.
You can merge.

**Comment by JMNordeste-dev** [comment]
@jonquil2002  Jordan? :)

**Pull request merged**
